name: core
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared:
    path: shared
  json_annotation: ^4.4.0
  sprintf: ^6.0.0
  get_storage: ^2.0.3
  flutter_svg: ^1.0.0
  flutter_cache_manager: ^3.3.0
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/icons/
    - assets/lottie/