name: base_flutter_getx
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  #http_parser: ^4.0.0
  #Firebase
  firebase_messaging: ^11.4.4
  firebase_core: ^1.19.1
  firebase_crashlytics: ^2.8.4
  shared_preferences: ^2.0.15
  get_storage: ^2.0.3
  sprintf: ^6.0.0
  event_bus: ^2.0.0
  url_launcher: ^6.1.4
  #Share
  get: ^4.6.5
  dio: ^4.0.6
  path: ^1.8.1
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.1+1
  flutter_cache_manager: ^3.3.0
  # Gallery
  file_picker: ^4.6.1
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  photo_manager: ^2.2.0-dev.1
  path_provider: ^2.0.11
  camera: ^0.9.8+1
  shimmer: ^2.0.0
  photo_view: ^0.14.0
  flutter_image_compress: ^1.1.0
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.10
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 180 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  colors:
    inputs:
      - assets/color/colors.xml
#flutter packages pub run build_runner build

flutter:
  uses-material-design: true
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
  assets:
    - assets/
    - assets/fonts/
    - assets/svg/
    - assets/svg/home/
    - assets/svg/camera/
    - assets/svg/document/
    - assets/svg/login/
    - assets/images/
    - assets/images/home/
    - assets/images/document/
    - assets/images/estimation/