///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class DPath {
  DPath._();

  static const String assetsDocument = 'assets/document';
  static const String favouriteIcHeart = 'assets/icons/favourite/ic_heart.svg';
  static const String favouriteIcHeartFill = 'assets/icons/favourite/ic_heart_fill.svg';
  static const String homeBgHomeAdd = 'assets/images/home/bg_home_add.svg';
  static const String homeIcCalendar = 'assets/icons/home/ic_calendar.svg';
  static const String homeIcDola = 'assets/icons/home/ic_dola.svg';
  static const String homeIcFiltter = 'assets/icons/home/ic_filtter.svg';
  static const String homeIcFiltterNoshadow = 'assets/icons/home/ic_filtter_noshadow.svg';
  static const String homeIcHome = 'assets/icons/home/ic_home.svg';
  static const String homeIcPlus = 'assets/icons/home/ic_plus.svg';
  static const String homeIcSearch = 'assets/icons/home/ic_search.svg';
  static const String homeIcShit = 'assets/icons/home/ic_shit.svg';
  static const String iconsIcLogo = 'assets/icons/ic_logo.svg';
  static const String iconsIcLogoPng = 'assets/icons/ic_logo_png.png';
  static const String imagesImgHomeSearch = 'assets/images/img_home_search.png';
  static const String imagesImgIcBack = 'assets/images/img_ic_back.png';
  static const String imagesImgIcClose = 'assets/images/img_ic_close.png';
  static const String imagesImgIcDown = 'assets/images/img_ic_down.png';
  static const String imagesImgTestMessage = 'assets/images/img_test_message.png';
  static const String imagesImgTestNotification = 'assets/images/img_test_notification.png';
  static const String imagesImgTextClose = 'assets/images/img_text_close.png';
  static const String imagesImgTextLogo = 'assets/images/img_text_logo.png';
  static const String itemDemo1 = 'assets/images/item/demo1.png';
  static const String itemDemo2 = 'assets/images/item/demo2.png';
  static const String itemDemo3 = 'assets/images/item/demo3.png';
  static const String itemIcEdit = 'assets/icons/item/ic_edit.svg';
  static const String itemIcEditImage = 'assets/icons/item/ic_edit_image.svg';
  static const String itemIcEraser = 'assets/icons/item/ic_eraser.svg';
  static const String itemIcRotate = 'assets/icons/item/ic_rotate.svg';
  static const String itemIcTrash = 'assets/icons/item/ic_trash.svg';
  static const String itemIcZoomIn = 'assets/icons/item/ic_zoom_in.svg';
  static const String itemIcZoomOut = 'assets/icons/item/ic_zoom_out.svg';
  static const String jsonCities = 'assets/json/cities.json';
  static const String jsonImageupload = 'assets/json/imageupload.json';
  static const String loginIcEmail = 'assets/icons/login/ic_email.svg';
  static const String loginIcFacebook = 'assets/icons/login/ic_facebook.svg';
  static const String loginIcGoogle = 'assets/icons/login/ic_google.svg';
  static const String loginIcInvisible = 'assets/icons/login/ic_invisible.svg';
  static const String loginIcLogincode = 'assets/icons/login/ic_logincode.svg';
  static const String loginIcPassword = 'assets/icons/login/ic_password.svg';
  static const String loginIcUsername = 'assets/icons/login/ic_username.svg';
  static const String loginIcVisible = 'assets/icons/login/ic_visible.svg';
  static const String loginImgWoman1 = 'assets/images/login/img_woman_1.webp';
  static const String loginImgWoman2 = 'assets/images/login/img_woman_2.webp';
  static const String loginImgWoman3 = 'assets/images/login/img_woman_3.webp';
  static const String lottieVestiumsJSON = 'assets/lottie/Vestiums_JSON.json';
  static const String profileIcCapture = 'assets/icons/profile/ic_capture.svg';

}
