///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class DPathCore {
  DPathCore._();

  static const String fontsRubikBold = 'assets/fonts/rubik_bold.ttf';
  static const String fontsRubikMedium = 'assets/fonts/rubik_medium.ttf';
  static const String fontsRubikRegular = 'assets/fonts/rubik_regular.ttf';
  static const String imagesImgIcEmpty = 'assets/images/img_empty.webp';
  static const String imagesImgDataError = 'assets/images/img_error.webp';
  static const String iconEmpty = 'assets/images/icon_empty.svg';
}
